### ISSUE TITLE
Inconsistent namespace between docs and yaml file

### ISSUE THREAD

**Issue by vnugent** [hawkular/hawkular-openshift-agent#157]
Example oc commands in this repo README and OpenShift doc[*] use `-n default` throughout, but `openshift-infra` is specified in deploy/openshift/config map.yaml 
https://github.com/hawkular/hawkular-openshift-agent/blob/master/deploy/openshift/hawkular-openshift-agent-configmap.yaml#L16

[*] OpenShift
https://docs.openshift.org/latest/install_config/cluster_metrics.html#deploying-hawkular-openshift-agent

**Comment by jmazzitelli** [comment]
@vnugent this is actually correct. The agent can (and we recommend it due to certain security issues I won't get into - but its about when running in multi-tenancy mode) run in "default" project whereas the h-metrics runs in openshift-infra. If you look at that link you supplied:

https://github.com/hawkular/hawkular-openshift-agent/blob/master/deploy/openshift/hawkular-openshift-agent-configmap.yaml#L16

It is referring to the secret of H-METRICS (not the agent) and H-Metrics *is* installed in openshift-infra:

`secret:openshift-infra/hawkular-metrics-account/hawkular-metrics.username`

That is referencing the H-Metrics secret - nothing to do with the hawkular agent.

So this is all correct. The agent gets deployed in "default" but h-metrics is in openshift-infra and the agent can refer to the h-metrics secret in openshift-infra in its configuration file.

**Comment by vnugent** [comment]
It makes sense now.  Thanks for the explanation.
