### ISSUE TITLE
tag metrics just like heapster?

### ISSUE THREAD

**Issue by jmazzitelli** [hawkular/hawkular-openshift-agent#17]
Hawkular-openshift-agent has the ability to define a tag to be applied globally (across all metrics collected by the agent), and define a tag to be applied to endpoint metrics (across all metrics emitted by an endpoint), and define a tag to be applied to an individual metric on an individual endpoint.

Should the hawkular-openshift-agent create default metric tags just like the hawkular heapster sink? See: https://github.com/kubernetes/heapster/tree/master/metrics/sinks/hawkular

Today, no tags are configured by default except all pod labels are converted to hawkular metric tags and placed on metrics that come from that pod. So if a pod has labels "label1=val1" and "label2=val2", then two identical tags are added to all metrics on all endpoints within that pod. I do not know if heapster does it that way - I think I heard it might concatenate all labels into a single comma-separated string (e.g. "label1=val1,label2=val2"). What should hawkular-openshift-agent do with pod labels?

What other tags do we need by default, if any? Is there a document that shows what the tags should be (their names and what the values are)? Or is there some examples that show all the heapster tags that we want to mimic?

(these questions can probably be answered by @mwringe and @burmanm)

**Comment by mwringe** [comment]
We need to have the same tags that Heapster applies by default to all metrics.

Please look at what heapster is currently collecting

**Comment by jmazzitelli** [comment]
> Please look at what heapster is currently collecting

Yes, this is my question :) Is there any documentation that describes all the heapster metrics? or examples/screenshots of them?

**Comment by jmazzitelli** [comment]
some heapster labels: https://github.com/kubernetes/heapster/blob/master/metrics/core/labels.go

**Comment by mwringe** [comment]
Or just grab metrics directly from what we are already storing.

Eg:
    {
        "dataRetention": 7,
        "id": "pod/8b6e8f08-a041-11e6-8494-c85b76045a27/network/rx_errors_rate",
        "maxTimestamp": 1478025555000,
        "minTimestamp": 1478011635000,
        "tags": {
            "descriptor_name": "network/rx_errors_rate",
            "group_id": "/network/rx_errors_rate",
            "host_id": "corbeau",
            "hostname": "corbeau",
            "labels": "metrics-infra:heapster,name:heapster",
            "namespace_id": "9e8eeeb0-9fa0-11e6-8494-c85b76045a27",
            "namespace_name": "openshift-infra",
            "nodename": "corbeau",
            "pod_id": "8b6e8f08-a041-11e6-8494-c85b76045a27",
            "pod_name": "heapster-0p0gn",
            "pod_namespace": "openshift-infra",
            "type": "pod"
        },
        "tenantId": "openshift-infra",
        "type": "gauge"
    }

We should have those same tags being applied to the metrics being gathered by the agent.

**Comment by jmazzitelli** [comment]
Hawkular OpenShift agent does now have the ability to tag most of those: labels, namespace_id, namespace_name, nodename, pod_id, pod_name, pod_namesapce.

The rest of these tags do not seem to be relevant for our use cases - in fact, the agent doesn't even have any data for the tag values. For example, AFAICS, things like "host_id" and "hostname" are valid only for containers (I guess these tags are placed on container metrics like "rx_errors_rate" in the example above). "group_id" is one I'm not sure about, but it also looks relevant only for container metrics since I see container data being used to build it here:

````
func (h *hawkularSink) groupName(ms *core.MetricSet, metricName string) string {
	n := []string{ms.Labels[core.LabelContainerName.Key], metricName}
	return strings.Join(n, separator)
}
...
mdd.Tags[groupTag] = h.groupName(ms, metric.Name)
````

"Type" looks to be an indicator of where the system metric came from (I think its valid values are: sys_container, pod_container, pod, ns, node, cluster) and since we are collecting app metrics on pod endpoints, not metrics from system entities like nodes, sys containers, and the like, this tag has no meaning for us.

"descriptor_name" seems to be a help text or metric description text? We have the ability to add that for each metric we define in the agent config maps (we do not define metrics in code since the metrics will be app specific and thus must be configured rather than hardcoded; as such, we can require the person that writes the config to specify a "descriptor_name" tag with a human readable description.

Another one I see in the heapster code is "container_base_image" - but that again is clearly container specific and thus not something I think we will even want to use (since we don't have container data to place in the tag value - we aren't collecting container-based system metrics).

**Comment by mwringe** [comment]
> For example, AFAICS, things like "host_id" and "hostname" are valid only for containers

The example post is for a pod level metric, there is nothing specific to docker containers being stored in there. The confusion may be that cadvisor has a different definition of what a container is (a running service on your machine is a type of 'container' to it) and technically pods are docker containers as well in you want to look down at the implementation level.

"hostname" have to do with machine the pod is running on. In this case "corbeau" is the hostname for my openshift node. "host_id" I think in most cases should be the hostname, but when running with a cloud provider, it may return an id that the cloud provider gives (I think, its been a while since I looked at this part more closely)

> "group_id" is one I'm not sure about

Yeah, I view this more as the 'metric type'. When I do a query like "give me metric FOO from pod with id BAR", the "group_id" corresponds to FOO here.

I think the reasoning here is that you could have multiple metrics with different metric names, but be considered under the same 'group' of metrics. For instance something like having a "group_id:cpu/usage" and then have individual metrics for each cpu core (but in this case we would also need some sort of 'metric_name' or 'metric_id' tag as well).

For custom metrics I don't know if this makes a lot of sense or not. It doesn't really work for Prometheus style endpoints nor for Jolokia endpoints. So I think we can skip this for custom metrics. If a user really wants to have something like this, they can define it in their metrics configuration to add this tag.

> "Type" looks to be an indicator of where the system metric came from (I think its valid values are: sys_container, pod_container, pod, ns, node, cluster) and since we are collecting app metrics on pod endpoints, not metrics from system entities like nodes, sys containers, and the like, this tag has no meaning for us.

We should still have this, even if its just set as 'type:pod' for all our metrics right now. It should show up in a list if someone requests all metrics being gathered at the pod level, and there is a good chance we may introduce other types later one.

> "descriptor_name" seems to be a help text or metric description text? We have the ability to add that for each metric we define in the agent config maps (we do not define metrics in code since the metrics will be app specific and thus must be configured rather than hardcoded; as such, we can require the person that writes the config to specify a "descriptor_name" tag with a human readable description.

Human readable content (name, description, units, etc) are really helpful for things like being able to nicely graph things or to view in a UI. We currently don't use them very well in Heapster at the moment.

> Another one I see in the heapster code is "container_base_image" - but that again is clearly container specific and thus not something I think we will even want to use (since we don't have container data to place in the tag value - we aren't collecting container-based system metrics).

Yes, this is for docker containers and we don't want to automatically add in this tag since the endpoints are pod specific and not docker container specific.

**Comment by mwringe** [comment]
I think this can be closed now. The tags we apply are more or less inline with what Heapster provides and we can access the metrics using similar queries.
