### ISSUE TITLE
Build docker image and openshift configuration

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#30]
We need to be able to package the Hawkular OpenShift Agent in a docker image and be able to deploy it to OpenShift.

**Comment by mwringe** [comment]
@jmazzitelli can you please assign this to me?

**Comment by jmazzitelli** [comment]
I merged PR #34 - I also added a little convenience script that you can run rather than going through the manual steps in the README. It probably isn't foolproof, but I use it successfully. There's probably more we can do (e.g. as mentioned in the PR, one day we should think about adding a "openshift-deploy" make target - perhaps today all it does is run the deploy/openshift/deploy-to-openshift.sh script?)

For now, consider the initial work complete and this issue can be closed. Any additional features or fixes we'll create new issues.
