### ISSUE TITLE
don't allow sensitive env vars to be used for replacement tokens in tags

### ISSUE THREAD

**Issue by jmazzitelli** [hawkular/hawkular-openshift-agent#36]
A tag value can support ${env} replacement tokens. But the agent has sensitive env vars (like passwords) so we don't want to allow that.

**Comment by jmazzitelli** [comment]
We should either take out entirely the env var replacement, or, if we want something like this, then can we just put this env var support in the agent global config? eg every pod gets a tag with that value? that way its the admin who manages the agent who gets to determine what extra tags to add based on envars.

**Comment by mwringe** [comment]
I don't think we would ever want a user who manages a pod to be able to specify something based on an envar of the agent. The user who manages a pod is not the admin who manages the agent, and they don't know what those envars are going to be.

If we want to support something like this, we could have the admin add this to the config.yaml, so that all pods get this tag added.

Of if we want something similar, we could have a list of hardcoded properties that a pod user could optionally add to their metrics if requested (although I am not sure of an example at the moment).

Do you have a specific usecase in mind for this feature?

**Comment by jmazzitelli** [comment]
I do not have a specific usecase in mind. One of those things where "Hey, I can do this" so I did it :)

**Comment by jmazzitelli** [comment]
turns out, this should be an easy fix.

https://github.com/hawkular/hawkular-openshift-agent/blob/af68fb96608fd822da8757b9c6784cdc67c26e12/collector/manager/metrics_collector_manager.go#L154-L158

````
globalTags := mcm.Config.Tags.ExpandTokens(true, additionalEnv) // <-- keep param 1 as TRUE
endpointTags := endpoint.Tags.ExpandTokens(false, additionalEnv) // <-- param 1 is now FALSE

for i, metric := range endpoint.Metrics {
	metricTags := metric.Tags.ExpandTokens(false, additionalEnv) // <-- param 1 is now FALSE
````
We'll let the admin use ${env} in the global agent config but we will not allow pods to use them. We just pass in "false" when expanding tokens in the above calls, except when expanding the global config, which we can pass in "true"

One use case can be that the agent can have an env var set to identify an agent with a custom string and have that agent ID be used as a tag. This means every metric that agent stores will be tagged with an agent identification string that the admin defines via env. var.

**Comment by jmazzitelli** [comment]
This is done. A user who manages a pod cannot use env vars for replacement tokens. Only the user that administers the agent itself can put env vars in the global tags (which are defined in the global agent config). See PR #37
