### ISSUE TITLE
Assign tags to metrics

### ISSUE THREAD

**Issue by jmazzitelli** [hawkular/hawkular-openshift-agent#4]
Right now, there is no way for endpoints/metrics to be configured with custom tags in Hawkular Metrics. The only tags the agent sends up are labels that are already on the Prometheus metrics themselves.

We need to tag metrics with pod specific things (like namespace) and we may even want to tag all metrics with a global agent tag (to indicate "this metric was stored by this agent").

@mwringe knows more about what specific tags we need to support.

**Comment by burmanm** [comment]
You should look at the implementation in heapster, that has the labels transformed to tags.

**Comment by mwringe** [comment]
yeah, we need to make sure its doing the same thing as Heapster so that when we do queries we get back the same results.

We also  want to have a 'collector' tag (or something like that) which will be the name and version of the collector.

We also probably want to give users the ability to add custom tags if they want by defining them in their endpoint definition configmap.

**Comment by jmazzitelli** [comment]
@burmanm  @mwringe  Can someone provide a link here to the Heapster code relevant for this issue? The person who eventually works on this issue will want to refer to the Heapster implementation if we are going to want to do what Heapster does.
