### ISSUE TITLE
Deploy images to docker hub

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#52]
We probably want to start pushing images to docker hub soon. This will make it much more easier for people to get started using the agent.

**Comment by jmazzitelli** [comment]
Who has access to put it up on the hawkular docker hub account?

**Comment by jmazzitelli** [comment]
yesterday I pushed hawkular/hawkular-openshift-agent:dev to docker hub: https://hub.docker.com/r/hawkular/hawkular-openshift-agent/

Do we want to do this automatically from travis? I don't know if that's possible since you need to docker login, but it would be nice to continually update docker hub with a new "dev" version everytime a new PR is merged into master. I'm not sure how to do this.

**Comment by mwringe** [comment]
Closing this issue as we now have docker images in docker hub. Another issue has been opened specifically for automating the process (https://github.com/hawkular/hawkular-openshift-agent/issues/68)
